### ISSUE TITLE
Update for elm-xml-decode 3.1.0

### ISSUE THREAD

**Issue by kyasu1** [ymtszw/elm-http-xml#2]
`Xml.Decode.oneOf`が使えなくておかしいなと気づいたのですが、可能であればこちらもアップデートしていただければ混乱しなくて良いかなと思いました！
よろしくお願いいたします。

**Comment by ymtszw** [comment]
`1.0.3`をリリースしました。こちらで`elm-xml-decode@3.x`が使用できます。
同時に`2.0.0`もリリースし、`elm/http@2.x`に対応しましたが、`Http.Request`の削除などAPIに後方非互換な変更が入ったのでmajor upgradeする場合は注意してください。

---

`1.0.3` is released, which now accepts `elm-xml-decode@3.x`.
Also `2.0.0` is released, with support of `elm/http@2.x`. However it removed `Http.Request`, resulting in backward-incompatible changes. Upgrade with care.

**Comment by ymtszw** [comment]
Cf. #1

**Comment by kyasu1** [comment]
ご対応ありがとうございました。
どちらもパッケージもとても役に立っています！

ところで、パッケージサイト上のデフォルトが`1.0.2`のままで、`2.0.0`での表記が以下のようになっています。反映に時間がかかるのかなと見ていましたが、お知らせまで…

<img width="659" alt="Screen Shot 2019-08-18 at 11 13 47" src="https://user-images.githubusercontent.com/890106/63219299-bb72af80-c1a9-11e9-9c4b-da3a13b0ca5e.png">
